backend/api/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import DeviceViewSet, DeviceAPIView, DeviceReadingViewSet

router = routers.DefaultRouter()
router.register(r'devices', DeviceViewSet)

urlpatterns = [
    path('devices/<str:uid>/', DeviceAPIView.as_view()),
    path('devices/<str:device_uid>/readings/<str:parameter>/', DeviceReadingViewSet.as_view({'get': 'list'})),
    path('', include(router.urls)),
]

backend/backend/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('home.urls')),
    path("__reload__/", include("django_browser_reload.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/home/urls.py
from django.urls import path
from .views import index, devices_graph

app_name = 'home'


urlpatterns = [
    path('', index, name='index'),
    path('devices-graph/<str:device_uid>/',devices_graph, name='devices_graph' )
]

backend/api/models.py
from django.db import models

# Create your models here.
class Device(models.Model):
    uid = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class TemperatureReading(models.Model):
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    temperature = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.temperature} ˚C"



class HumidityReading(models.Model):
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    humidity = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.humidity} %"

backend/home/models.py
from django.db import models

# Create your models here.

backend/api/views.py
from django.shortcuts import render
from datetime import datetime
from rest_framework import viewsets, status
from .models import Device, HumidityReading, TemperatureReading
from .serializers import DeviceSerializer
from rest_framework.response import Response
from rest_framework.generics import RetrieveAPIView, RetrieveUpdateDestroyAPIView
from .serializers import HumidityReadingSerializer, TemperatureReadingSerializer


class DeviceViewSet(viewsets.ModelViewSet):
    queryset = Device.objects.all()
    serializer_class = DeviceSerializer
    lookup_field = 'uid'

    def destroy(self, request, *args, **kwargs):
        instance = self.get_object()
        self.perform_destroy(instance)
        return Response(status=status.HTTP_204_NO_CONTENT)

    def retrieve(self, request, pk=None):
        device = self.get_object()
        serializer = DeviceSerializer(device)
        return Response(serializer.data)

class DeviceAPIView(RetrieveUpdateDestroyAPIView):
    queryset = Device.objects.all()
    serializer_class = DeviceSerializer
    lookup_field = 'uid'

class DeviceReadingViewSet(viewsets.ViewSet):
    def list(self, request, device_uid, parameter):
        try:
            device = Device.objects.get(uid=device_uid)
        except Device.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)
        
        print(request.GET)
        print(device_uid)
        print(parameter)

        start_on = datetime.strptime(request.GET.get('start_on'), '%Y-%m-%dT%H:%M:%S')
        end_on = datetime.strptime(request.GET.get('end_on'), '%Y-%m-%dT%H:%M:%S')

        if parameter == 'temperature':
            readings = TemperatureReading.objects.filter(
                device=device, created_at__range=(start_on, end_on)
            )
            serializer = TemperatureReadingSerializer(readings, many=True)
        elif parameter == 'humidity':
            readings = HumidityReading.objects.filter(
                device=device, created_at__range=(start_on, end_on)
            )
            serializer = HumidityReadingSerializer(readings, many=True)
        else:
            return Response(status=status.HTTP_400_BAD_REQUEST)

        return Response(serializer.data)

backend/home/views.py
from django.shortcuts import render
from api.models import Device, HumidityReading, TemperatureReading
import requests
import json

# Create your views here.
def index(request):
    url = "http://127.0.0.1:8000/api/devices"

    response = requests.get(url)
    # print(response.json())

    res = requests.get(url + '/4718dc2d-b2f2-43df-8436-f5845acfca50/readings/humidity/?start_on=2023-01-25T00:00:00&end_on=2023-01-31T23:59:59')
    # print(res.json())
    context = {
        'devices' : response.json(),
        'device_data': res.json()
    }
    return render(request,'index.html', context=context)

def devices_graph(request, device_uid=None):
    url = "http://127.0.0.1:8000/api/"
    humidity = requests.get(url + f'devices/{device_uid}/readings/humidity/?start_on=2023-01-25T00:00:00&end_on=2023-01-31T23:59:59')
    temp = requests.get(url + f'devices/{device_uid}/readings/temperature/?start_on=2023-01-25T00:00:00&end_on=2023-01-31T23:59:59')
    # print(temp.json())
    # for x in temp.json():
        # print(x.get('temperature'))


    data = [{"time":"2023-01-25T00:00:00"},
            {"time":"2023-01-24T00:00:00"},
            {"time":"2023-01-23T00:00:00"},
            {"time":"2023-01-26T00:00:00"},
            {"time":"2023-01-27T00:00:00"}]
    json_data = json.dumps(data)
    temp = json.dumps(temp.json())
    humidity = json.dumps(humidity.json())
    context = {
        'humidity' : humidity,
        'temp' : temp,
        'json_data': json_data,
    }
    # print(device_uid)
    # print(request.GET)
    # print(context)
    
    return render(request, 'device-graph.html', context)

backend/home/templates/base.html
<!DOCTYPE html>
{% load tailwind_tags %}
{% load static %}
<html lang="en">
<head>
    {% tailwind_css %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/script.js' %}" ></script>
    <title>Weather</title>
</head>
<body> 
    {%block content%}   
    {%endblock content%}   
    {%block scripts%}
    {%endblock scripts%}
</body>
</html>

backend/home/templates/device-graph.html
{% extends 'base.html' %}
{% block content %}
<div class="flex space-x-2">
    <a href="/">
    <button
      type="button"
      data-mdb-ripple="true"
      data-mdb-ripple-color="light"
      class="inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
    >Go Back</button>
</a>
  </div>
<div class="shadow-lg rounded-lg overflow-hidden">
    <div class="py-3 px-5 bg-gray-50 text-center text-5xl">Device Graph</div>  
  <!-- Required chart.js -->
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  
  <!-- Chart bar -->
<!-- my_template.html -->
        <canvas id="myChart"></canvas>
        <script>
            var ctx = document.getElementById('myChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [{{ json_data|safe }}][0].map(item => item.time),
                    datasets: [{
                        label: 'Temperature',
                        data: [{{ temp|safe }}][0].map(item => item.temperature),
                        backgroundColor: 'rgba(255, 99, 132, 0.2)',
                        borderColor: 'rgba(255, 99, 132, 1)',
                        borderWidth: 1
                    },{
                        label: 'Humidity',
                        data: [{{ humidity|safe }}][0].map(item => item.humidity),
                        backgroundColor: 'rgba(75, 192, 192, 0.2)',
                        borderColor: 'rgba(75, 192, 192, 1)',
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        y: {
                            ticks: {
                                beginAtZero: true
                            }
                        }
                    }
                }
            });
        </script>

      </div>
{% comment %} 
      {{temp}}
      {{ json_data}}

                   {% endcomment %}
{% endblock content %}

backend/home/templates/index.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<h1 class="text-center text-5xl">Devices</h1>
<div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
        <div class="overflow-hidden">
          <table class="min-w-full">
            <thead class="bg-white border-b">
              <tr>
                
                <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                  Device UID
                </th>
                <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                  Device Name
                </th>
            
              </tr>
            </thead>
{% for device in devices %}

            <tbody>

              <tr class=" border-b">
                <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                    <a href="{% url 'home:devices_graph' device.uid %}">
                {{ device.uid }}
                    </a>            
                </td>
                <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                    {{ device.name }}

                </td>
            
              </tr>

            </tbody>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </div>

<br><br>


<a href="api/" class="bg-slate-500"> <h3 class=""> Click for api endpoints</h3></a>

{% comment %} <form action = "" method = "get">
    {% csrf_token %}
    Select Date and Time<br><input type="datetime-local" name="datetime"><br>
    <input type="submit" value="Submit">
</form> {% endcomment %}
{% endblock content %}

backend/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>